### PR TITLE
updated chalk from 1.1.3 to 2.3.0

### PR DESCRIPTION
**Pull request by bompus**
chalk has had many improvements. For my case, I needed the ability to specify yellowBright color, which the older version of chalk did not support for me on Windows at least. Being able to use a wider range of colors really makes the tables pop.

### CODE REVIEW

**Comment by soyuka** [comment]
Because of pm2 we have a nodejs version constraint >= 0.12 which isn't supported by this new version of chalk. I'm not sure when we can drop `0.12`. @vmarchaud any idea?

**Comment by vmarchaud** [comment]
We have planned to drop 0.12 for PM2 3.0 but currently it's not possible

**Comment by soyuka** [comment]
Thanks @vmarchaud keeping this open since then.

**Comment by Unitech** [comment]
upgraded to 3.x

**Pull request closed without merging**
